[language-server.expert]
command = "/usr/local/bin/expert_darwin_arm64 --stdio"

[[language]]
name="elixir"

[[language]]
name="javascript"

# Deno Language Server
[language-server.deno]
command = "deno"
args = ["lsp"]

# Javascript
[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

# Typescript
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

# Python
[[language]]
name = "python"
language-servers = ["pyright"]

# For TailwindCSS
[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
